version: '3.8'

services:
  elasticsearch-hot:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch-hot
    environment:
      - node.name=es-hot
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-warm
      - cluster.initial_master_nodes=es-hot
      - node.roles=master,data,data_hot,ingest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-hot-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-stack

  elasticsearch-warm:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch-warm
    environment:
      - node.name=es-warm
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-warm
      - node.roles=data_warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-warm-data:/usr/share/elasticsearch/data
    networks:
      - elastic-stack

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - elastic-stack
    depends_on:
      - elasticsearch-hot

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-hot:9200
      - xpack.security.enabled=false
    networks:
      - elastic-stack
    depends_on:
      - elasticsearch-hot

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.2
    container_name: filebeat
    user: root # Необходим для чтения логов docker и docker.sock
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elastic-stack
    depends_on:
      - logstash

volumes:
  es-hot-data:
  es-warm-data:

networks:
  elastic-stack:
    driver: bridge