input {
 
  beats {
    port => 5044
  }
  
  
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  
  if [container] {
    mutate {
      add_tag => ["docker_container_log"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
  
 
  # stdout { codec => rubydebug }
}
